### ISSUE TITLE
 Note: There was an error unfollowing padeirotv, please try again later.

### ISSUE THREAD

**Issue by yuriccosta** [rjruizfdez/insta-unfollow#31] opened 2021-03-13 15:13 UTC
## Expected vs Actual Behavior
It unfollow everyone who does not follow me, but it cant unfollow anyone
## Specifications

 - Operative system:
Linux
 - Version (e.g. Python version):
python 2.7 and python 3

## Steps to Reproduce the Problem
python main.py -u myuser -p mypassword -o super-unfollow

**Comment by ricardojoserf** [comment] 2021-03-21 19:17
Hi @zzAlfa . Could you try this again after waiting for some hours or maybe even other day? That may be because your account had many interactions and it is necessary to wait because the instagram limit was reached

**Comment by ricardojoserf** [comment] 2021-03-23 08:46
Hi @zzAlfa , any update please? :)

**Comment by ricardojoserf** [comment] 2021-03-23 17:44
Hi! I close this as it is a duplicate of #33, and that one was solved just waiting some hours. If not, let me know and I will reopen the issue

**Closed as completed by ricardojoserf** 2021-03-23 17:44 UTC
Labels: bug
