### ISSUE TITLE
AttributeError: 'InstagramAPI' object has no attribute 'username_id'

### ISSUE THREAD

**Issue by felipeschiavon** [rjruizfdez/insta-unfollow#37] opened 2021-04-24 18:06 UTC
## Expected vs Actual Behavior

Hello, first of all, thanks for your work! I wasn't able to run this command:

`python main.py -u USERNAME -p PASSWORD -o super-unfollow`

Log:

```
Login not successful
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    main()
  File "main.py", line 143, in main
    for i in api.getTotalSelfFollowers():
  File "C:\Users\felip\Downloads\nao-deu-instagram-followers-bot-master\LevPasha\InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: 'InstagramAPI' object has no attribute 'username_id'
```

## Specifications

 - Operative system:
Windows 10

 - Version (e.g. Python version):
Python 3.7.6

## Steps to Reproduce the Problem

Thanks for your help!

**Comment by ricardojoserf** [comment] 2021-04-24 20:30
Hi @felipeschiavon !!! It seems the login was not successful. Could you test again and check if the credentials are right? Or test using other account? :)

**Comment by felipeschiavon** [comment] 2021-04-24 21:08
You are right. It's working now, my bad!
But I noticed that it is unfollowing profiles that follow me, don't know why.
I used: `python main.py -u USERNAME -p PASSWORD -o super-unfollow`

**Comment by ricardojoserf** [comment] 2021-04-24 21:12
Hi @felipeschiavon , that is very weird, it should not do that. Do you think maybe you used "unfollow-all" instead of "super-unfollow"?

**Comment by felipeschiavon** [comment] 2021-04-24 21:19
Hi @ricardojoserf. Thanks! I checked again and I really used super-unfollow. I did it twice and I noticed that more than one profile was unfollowed, but it was a follower.

**Comment by ricardojoserf** [comment] 2021-04-24 21:38
Hi @felipeschiavon , I tested this with my account and it does not happen in my case. I will leave the issue open some days in case someone else has this same problem, to see if we can find out the cause (the code is very simple so it is not the cause).

**Comment by felipeschiavon** [comment] 2021-04-24 22:07
Ok, thanks for answering @ricardojoserf. I verified that even asking for report (`python main.py -u USERNAME -p PASSWORD -o info`) gives me, at the beginning (I follow them but they dont follow me:) a list with a lot of users that follow me.

BTW, I was able to unfollow some users, but now I think Instagram blocked for a while. After around 80 unfollows I got an error and couldn't unfollow again. I think this is expected right? I guess it's Instagram blocking...

The message I get is: `Note: There was an error unfollowing USER, please try again later.`

**Comment by ricardojoserf** [comment] 2021-04-26 07:47
Hi @felipeschiavon . Yes it is the Instagram limit, you can not use tools like this very frequently or you may get banned.
I close this by now until someone else gets the same results, I am unable to reproduce the problem yet xD

**Closed as completed by ricardojoserf** 2021-04-26 07:47 UTC
Labels: bug
